export const listingsData = [
  {
    id: 1,
    title: "Large 4-room apartment with a beautiful terrace",
    price: "$320,000",
    location: "West Legon",
    image: "/image-1.jpg",
  },
  {
    id: 2,
    title: "5i large design apartment with terrace",
    price: "$520,000",
    location: "Ashongman",
    image: "/image-2.jpg",
  },
  {
    id: 3,
    title: "5 bedroom house for sale at Adenta West",
    price: "$500,000",
    location: "Adenta",
    image: "/image-3.jpg",
  },
  {
    id: 4,
    title: "4 bedroom house for sale at East Legon Hills",
    price: "$320,000",
    location: "East Legon",
    image: "/image-4.jpg",
  },
  {
    id: 5,
    title: "Magnificent duplex in a private villa",
    price: "$520,000",
    location: "West Legon",
    image: "/image-5.jpg",
  },
  {
    id: 6,
    title: "6 bedroom-house at Limanyiri ",
    price: "$1,220,000",
    location: "Limanyiri",
    image: "/image-6.jpg",
  },
  {
    id: 7,
    title: "5i large design apartment with terrace",
    price: "$320,000",
    location: "West Legon",
    image: "/image-7.jpg",
  },
  {
    id: 8,
    title: "6 bedroom-house at Limanyiri",
    price: "$320,000",
    location: "Jahan Residential Area",
    image: "/image-8.jpg",
  },
  {
    id: 9,
    title: "Large 4-room apartment with a beautiful terrace",
    price: "$$320,000",
    location: "Dome",
    image: "/image-9.jpg",
  },
  {
    id: 10,
    title: "5 bedroom house for sale at Adenta West",
    price: "$320,000",
    location: "Pokuase",
    image: "/image-10.jpg",
  },
  {
    id: 11,
    title: "Large 4-room apartment with a beautiful terrace",
    price: "$820,000",
    location: "Achimota",
    image: "/image-11.jpg",
  },
  {
    id: 12,
    title: "4 bedroom house for sale at East Legon Hills",
    price: "$520,000",
    location: "East Legon",
    image: "/image-12.jpg",
  },
];
